config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CV Miguel Rodriguez</title>
</head>
<body class="container mx-auto w-4/5 md:w-3/4 lg:w-3/5 opacity-80">

<header>
  <div aria-hidden="true" class="mt-40"></div>
</header>

<div class="intro-info mb-6">
  <span class="text-2xl pb-4 font-medium tracking-wide">Miguel Rodríguez</span><br>
  <span>Designer and Developer</span><br>
  <span class="text-gray-500 font-medium">Based in Madrid</span><br><br>
  <a class="url url1 underline" href="mailto:aphex95@gmail.com" target="_blank">Send me an email</a><br>
  <a class="url url2 underline" href="https://www.linkedin.com/in/mglnglx" target="_blank">LinkedIn</a><br>
  <a class="url url3 underline" href="https://www.github.com/mglnglxx" target="_blank">Github</a><br>
  <a class="url url4 underline" href="https://drive.google.com/file/d/1o6D5u9O2F3u-47ss33AbXhbXMK9XDnX4/view?usp=sharing" target="_blank">Resume</a>

</div>

<p><span class="cursive">Iterating towards tangible realities.</span> Transforming legacy projects into modern digital experiences. Thinking about the human-centered approach to
design, collaborative work, and seamless digital products. Mostly working now with <span class="figma">Figma</span>, <span class="ruby">Ruby on Rails</span>, <span class="js">JS</span>, <span class="html5">HTML</span> and <span class="tailwindcss">Tailwind CSS</span>. </p>

<div class="grid sm:grid-cols-1 md:grid-cols-3 md:gap-8 lg:gap-4 lg:grid-cols-4 mt-10 mb-10 text-gray-500">
  <div class="mb-10">
    <span class="font-medium text-black lg:text-gray-500 lg:font-normal">Select Work</span>

    <a class="underline" href="https://mglnglx.notion.site/Miguel-Rodr-guez-Filiatly-Work-c42c5af45f184217830a6f60227d1f39" target="_blank"><p class="url font-medium mt-10 filiatly">Filiatly</p></a>
    <p class="leading-7">Product Design: Influencer Marketing Platform and Mobile App</p>

    <a class="underline" href="https://mglnglx.medium.com/ux-ui-case-study-infoportal-adapting-to-bureaucracy-4616ce132b9b" target="_blank"><p class="url font-medium mt-10 infoportal">Infoportal</p></a>
    <p class="leading-7">UX UI Case Study: Adapting to bureaucracy</p>

    <a class="underline" href="https://mglnglx.medium.com/ux-ui-case-study-wellness-pace-6f6cbb81b75d" target="_blank"><p class="url font-medium mt-10 pace">Pace</p></a>
    <p class="leading-7">UX UI Case Study on Wellness</p>

    <a class="underline" href="https://mglnglx.medium.com/ux-case-study-shazam-new-feature-8ff2a56a5cc8" target="_blank"><p class="url font-medium mt-10 shazam">Shazam</p></a>
    <p class="leading-7">UX UI Case Study: Shazam - New Feature</p>

    <a class="underline" href="https://www.savealexandria.xyz" target="_blank"><p class="url font-medium mt-10 alexandria">Alexandria</p></a>
    <p class="leading-7">Break even point calculator built on Rails and Tailwind CSS</p>

    <a class="underline" href="https://oceanbnb.herokuapp.com" target="_blank"><p class="url font-medium mt-10 oceanbnb">Oceanbnb</p></a>
    <p class="leading-7">Airbnb Clone built on Rails and JS</p>


  </div>

  <div class="col-span-2 mb-10">
    <span class="font-medium text-black lg:text-gray-500 lg:font-normal">Experience</span>
    <div>
      <ul class="mt-10">
      <li class="text-gray-900">Head of Product</li>
      <li class="text-gray-800">Elite Training</li>
      <li>Remote</li>
      <li>Aug 2021 - Present</li>
      <li class="text-gray-700">Innovation and revamp of the Communication, Marketing and Product departments in the company.</li>
      </ul>
    </div>

    <div>
      <ul class="mt-10">
        <li class="text-gray-900">UX UI Designer</li>
        <li class="text-gray-800">Filiatly</li>
        <li>Madrid, Spain</li>
        <li>Apr 2020 - Aug 2021</li>
        <li class="text-gray-700">Full UX/UI design process and development of an Influencer Marketing SaaS platform.</li>
      </ul>
    </div>

    <div>
      <ul class="mt-10">
        <li class="text-gray-900">Design Consultant</li>
        <li class="text-gray-800">Elite Training</li>
        <li>Remote</li>
        <li>Jul 2019 - Jan 2020</li>
        <li class="text-gray-700">Brand identity and design process development based on Agile, SCRUM and UX/UI methodologies.</li>
      </ul>
    </div>

    <div>
      <ul class="mt-10">
        <li class="text-gray-900">Sales and Customer Service Agent</li>
        <li class="text-gray-800">Concentrix</li>
        <li>Bogotá, Colombia</li>
        <li>Nov 2017 - Aug 2018</li>
    </div>
</div>

  <div class="lg:pl-8 md:pl-0">
    <span class="font-medium text-black lg:text-gray-500 lg:font-normal">Education</span>
    <ul class="mt-10">
      <li class="text-gray-900">Web Development Bootcamp</li>
      <li class="text-gray-700">Le Wagon Madrid</li>
      <li>Madrid, Spain</li>
      <li>Oct 2021 - Dec 2021</li>
    </ul>

    <ul class="mt-10">
      <li class="text-gray-900">UX UI Full Time Bootcamp</li>
      <li class="text-gray-700">Ironhack Madrid</li>
      <li>Madrid, Spain</li>
      <li>Jan 2020 - Mar 2020</li>
    </ul>

    <ul class="mt-10">
      <li class="text-gray-900">Communication Design Labs Masters</li>
      <li class="text-gray-700">IED Madrid</li>
      <li>Madrid, Spain</li>
      <li>Jan 2019 - Dec 2019</li>
    </ul>

    <ul class="mt-10">
      <li class="text-gray-900">Design Major - Communication Minor</li>
      <li class="text-gray-700">Universidad de los Andes</li>
      <li>Bogotá, Colombia</li>
      <li>2011 - 2018</li>
    </ul>
  </div>
</div>

</body>
</html>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miguel Rodríguez</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>